import { handleSlackEvent } from "@/slack-webhook-handler";
import { handleSlackInteractivity } from "@/slack-interactivity-handler";
import { JWKS_PATH } from "@dynamicagents/g2a-protocol";
import { getPublicJwks } from "@/auth/agent-outbound";
import {
  handleRemoteAgentNotification,
  NOTIFICATIONS_PATH
} from "@/a2a/notifications/remote";

// Cloudflare resolves Workflow + Durable Object class_names (wrangler.jsonc)
// from the entry module's exports.
export { MessageWorkflow } from "./workflows/message";
export { LifecycleWorkflow } from "./workflows/lifecycle";
export { ReconcileWorkflow } from "./workflows/reconcile";
export { ReactionWorkflow } from "./workflows/reaction";
export { CancelWorkflow } from "./workflows/cancel";
export { MaintenanceWorkflow } from "./workflows/maintenance";

// In-repo agents — each is its own A2A server. The Message Workflow reaches them
// in-process via their DO `stub.fetch` (see src/agents/dispatch.ts); they need no
// public HTTP route in Phase 3. Phase 3 echoes; Phase 4/5 add the AI loop + tools.
export { AdminAgent } from "./agents/admin";
export { OnboardingAgent } from "./agents/onboarding";

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const url = new URL(request.url);

    // Public JWKS — the gateway's Ed25519 signing public key(s). Remote (custom)
    // A2A agents fetch this to verify the gateway-identity JWT on each request.
    // Only public key material is ever exposed; no secret is shared.
    if (request.method === "GET" && url.pathname === JWKS_PATH) {
      return Response.json(getPublicJwks(), {
        headers: { "cache-control": "public, max-age=3600" }
      });
    }

    // Slack webhook ingest — verify the signature, classify the event, trigger
    // the matching durable Workflow, and ack within Slack's 3s budget. All agent
    // work happens asynchronously inside the Workflow, never inline here. The
    // gateway's public origin (JWT issuer/jku anchor) is discovered inside
    // handleSlackEvent, only after the Slack signature has been verified.
    if (request.method === "POST" && url.pathname === "/slack/events") {
      return handleSlackEvent(request, ctx);
    }

    // Slack Interactivity ingress — button clicks, select menus, and modal
    // submissions from the human-in-the-loop prompts. Configured as the app's
    // Interactivity Request URL (separate from the Events Request URL above, but
    // sharing the same signing-secret verification). Verifies + acks within 3s;
    // the approval/answer is routed back onto the paused A2A task off-path.
    if (request.method === "POST" && url.pathname === "/slack/interactivity") {
      return handleSlackInteractivity(request, ctx);
    }

    // Remote-agent push-notification callback — a custom agent POSTs its terminal
    // A2A Task here when its (possibly long) generation is done. The handler
    // authenticates the caller against its pinned card key + per-task token before
    // posting the reply to Slack. This is what replaced the old synchronous
    // "gateway blocks up to 30s for the reply" remote path.
    if (request.method === "POST" && url.pathname === NOTIFICATIONS_PATH) {
      return handleRemoteAgentNotification(request);
    }

    // Agent avatars — generated by the admin agent and stored in its
    // per-workspace DO (`admin:{wsId}`), keyed by agent name. DOs aren't publicly
    // reachable, so this route forwards to the right instance by wsId, which
    // returns the bytes (or 404) with a long immutable cache.
    // Path: /icons/{wsId}/{name}/{key}.{ext} — {key} is a 16-char content-hash
    // (see AdminAgent.putIcon). Pin the exact shape: a single trailing segment
    // with no further slashes, so unrelated GETs (e.g. the A2A AgentCard at
    // /icons/{wsId}/admin/.well-known/agent-card.json) are never forwarded.
    const icon = url.pathname.match(
      /^\/icons\/(\d+)\/[a-z0-9_-]+\/[a-f0-9]{16}\.[a-z0-9]+$/
    );
    if (request.method === "GET" && icon) {
      const ns = env.AdminAgent;
      const stub = ns.get(ns.idFromName(`admin:${icon[1]}`));
      return stub.fetch(request);
    }

    return new Response("Not found", { status: 404 });
  },

  // Cron reconciliation (wrangler triggers.crons): the convergence backstop that
  // repairs registry drift against Slack reality. Errors are logged, not
  // rethrown — a failed run just retries on the next tick.
  async scheduled(_controller: ScheduledController, env: Env) {
    try {
      const instance = await env.RECONCILE_WORKFLOW.create({});
      console.log("Reconciliation workflow triggered", {
        id: instance.id
      });
    } catch (err) {
      console.error("Reconciliation failed", err);
    }
    try {
      const instance = await env.MAINTENANCE_WORKFLOW.create({});
      console.log("Maintenance workflow triggered", {
        id: instance.id
      });
    } catch (err) {
      console.error("Maintenance failed", err);
    }
  }
} satisfies ExportedHandler<Env>;
